### PR TITLE
introduces .gemspec and Gemfile for easier development setup

### PR DESCRIPTION
**Pull request by benzimmer**
`bundle install` installs all gems needed for working on vines.

I needed to change the required eventmachine version to '1.0.0.beta.4' because the used em-http-request version 1.0.1 also depends on it.

would close issue #3

### CODE REVIEW

**Comment by benlangfeld** [comment]
+1

I would go further and add the bundler rake tasks.

**Comment by dgraham** [comment]
I'm hesitant to add this because it implies `gem build` is the right way to build and push the vines gem.  It needs to be built by saying `rake` so that the generated web resources are included in the gem.  I haven't seen a good way to handle files generated during the build with bundler.

**Comment by benlangfeld** [comment]
At the very least, the gemspec should be included in the repo rather than generated, with the Gemfile pointing to the gemspec (0fec25a). The rake tasks are less important IMO.

**Comment by benlangfeld** [comment]
Any chance of this being merged?

**Comment by dgraham** [comment]
Thanks, Ben!

**Pull request merged**
